[package]
name = "rsi_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rdkafka = { version = "0.29", features = ["tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"